name 'bubble'
maintainer 'Schuberg Philis'
maintainer_email 'fneubauer@schubergphilis.com'
license 'All rights reserved'
description 'Installs/Configures the "bubble" for developing'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.1.0'

depends 'parted'
depends 'nfs'
depends 'users'
depends 'supervisor'
depends 'tar'
depends 'sudo'
depends 'chef-client'
depends 'python'
